# Generated by Django 5.1.3 on 2024-11-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kioskoapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='categorias',
            name='nombre',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
