# Generated by Django 5.1.3 on 2024-11-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kioskoapi', '0002_marcas_alter_categorias_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
    ]
