# Generated by Django 5.1.3 on 2024-11-14 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kioskoapi', '0004_alter_categorias_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kioskoapi.marcas'),
        ),
    ]
