# Generated by Django 5.1.3 on 2024-11-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kioskoapi', '0006_productos_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='imagen',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
