# Generated by Django 5.1.3 on 2024-11-16 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kioskoapi', '0007_categorias_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destacados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kioskoapi.productos')),
            ],
        ),
    ]
